apiVersion: v1
kind: Secret
metadata:
  name: petstore-secrets
  namespace: petstore
  labels:
    app.kubernetes.io/part-of: petstore-platform
type: Opaque
stringData:
  postgres-password: "PetStore2026SecureDbPass!"
  jwt-secret: "dGhpcy1pcy1hLXNlY3VyZS1qd3Qtc2VjcmV0LWZvci1wZXQtc3RvcmUtdjEtZGV2ZWxvcG1lbnQtdGVzdC1rZXk="
