apiVersion: v1
kind: ConfigMap
metadata:
  name: petstore-config
  namespace: petstore
  labels:
    app.kubernetes.io/part-of: petstore-platform
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  USER_SERVICE_URL: "http://user-service:8081"
  CATALOG_SERVICE_URL: "http://catalog-service:8082"
  INVENTORY_SERVICE_URL: "http://inventory-service:8084"
  ORDER_SERVICE_URL: "http://order-service:8083"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8085"
  API_GATEWAY_URL: "http://api-gateway:8080"
  OTEL_SDK_DISABLED: "true"
  GCS_BUCKET_NAME: "petstore-app-1788943786-media"
