apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: petstore
  labels:
    app: notification-service
    app.kubernetes.io/part-of: petstore-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: us-central1-docker.pkg.dev/petstore-app-1788943786/petstore-repo/notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
              name: http
          env:
            - name: PORT
              value: "8085"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: OTEL_SDK_DISABLED
              value: "true"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 40
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: petstore
  labels:
    app: notification-service
spec:
  ports:
    - port: 8085
      targetPort: 8085
      name: http
  selector:
    app: notification-service
