apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: petstore
  labels:
    app: api-gateway
    app.kubernetes.io/part-of: petstore-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: us-central1-docker.pkg.dev/petstore-app-1788943786/petstore-repo/api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PORT
              value: "8080"
            - name: USER_SERVICE_URL
              value: "http://user-service:8081"
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service:8082"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:8083"
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service:8084"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: petstore-secrets
                  key: jwt-secret
            - name: OTEL_SDK_DISABLED
              value: "true"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-gateway-backendconfig
  namespace: petstore
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /actuator/health
    port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: petstore
  labels:
    app: api-gateway
  annotations:
    cloud.google.com/backend-config: '{"default": "api-gateway-backendconfig"}'
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: api-gateway
