input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if ![service] {
    mutate {
      add_field => { "service" => "unknown-service" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "petstore-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug { metadata => false }
  }
}
